name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10.12, 3.11.6, 3.12.0]
        environment: [production, development]
        extra-groups: ["", "dev,bench"]
    services:
      docker:
        image: docker:20.10.24
        options: --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build \
            --build-arg PYTHON_VERSION=${{ matrix.python-version }} \
            --build-arg UV_PROJECT_ENVIRONMENT=${{ matrix.environment }} \
            --build-arg UV_EXTRA_GROUPS=${{ matrix.extra-groups }} \
            -t generic-project:${{ matrix.environment }} .

      - name: Run Tests
        run: |
          docker run generic-project:${{ matrix.environment }} python -m unittest discover -s tests -p "*.py"
