services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        UV_PROJECT_ENVIRONMENT: development
        PYTHON_VERSION: 3.12.0
        UV_EXTRA_GROUPS: "dev,bench"
    environment:
      - UV_PROJECT_ENVIRONMENT=development
    volumes:
      - .:/app
    command: python -m src.main